config/routes.rb
Rails.application.routes.draw do
  devise_for :users, module: :users, controllers: {
    :registrations => 'users/registrations',
    :omniauth_callbacks =>  "users/omniauth_callbacks"
  }

  devise_scope :user do
    scope :signup do
      get '/' => 'users/registrations#signup'
      get '/registration' => 'users/registrations#registration'
      get '/sms_confirmation' => 'users/registrations#sms_confirmation'
      get '/sms_confirmation/sms/' => 'users/registrations#sms_confirmation_check'
      get '/address_confirmation' => 'users/registrations#address_confirmation'
      get '/card_confirmation' => 'users/registrations#card_confirmation'
      post '/complete' => 'users/registrations#complete'
    end
  end
  resources :mypage, only: :index do
    collection do
      get 'notification' => 'mypage#notification'
      get 'todo' => 'mypage#todo'
      get 'purchase' => 'mypage#purchase'
      get 'purchased' => 'mypage#purchased'
      get 'logout' => 'mypage#logout'
      get 'identification' =>'mypage#identification'
      get 'profile' => 'mypage#profile'
      patch 'profile_update' => 'mypage#profile_update'
      patch 'identification_update' => 'mypage#identification_update'
      namespace :card do
        get '/' => '/mypage/card#show'
        get 'create' => '/mypage/card#edit'
        post 'update' => '/mypage/card#update'
      end
      namespace :listings do
        get 'listing' => '/mypage/listings#listing'
        get 'in_progress' => '/mypage/listings#in_progress'
        get 'completed' => '/mypage/listings#completed'
      end
      namespace :review do
        get 'history' => '/mypage/reviews#index'
        get 'history/great' => '/mypage/reviews#great'
        get 'history/good' => '/mypage/reviews#good'
        get 'history/poor' => '/mypage/reviews#poor'
      end
      namespace :nice do
        get 'history' => '/mypage/nices#index'
      end
    end
  end

  resources :category, only: :show
  resources :brand, only: :show
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :trade, except: :index do
    collection do
      post 'pay/:id' => 'products#pay', as: 'pay'
    end
  end

  resources :products, except: :index do
    collection do
      get 'search'
    end
  end


  resources :products, except: :index do
    member do
      get :confirmation
    end
  end
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products, except: :index
  resource :card, controller: :card do
    collection do
      post 'pay/:id' => 'card#pay', as: 'pay'
    end
  end




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "homes#index"
  get 'products/:id/edit' => 'products#update'

end

app/controllers/mypage/card_controller.rb
class Mypage::CardController < CardController
  require "payjp"
  before_action :user_signed_in_check
  before_action :user_selected
  before_action :get_payjp_info, only: [:update, :show]
  
  def show
    card = current_user.credit_card
    if card.present?
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  def edit
  end

  def update
    if params['payjp-token'].blank?
      redirect_to action: "edit", id: current_user.id
    else
      customer = Payjp::Customer.create(
      email: current_user.email,
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      )
      @card = CreditCard.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "edit", id: current_user.id
      end
    end
  end

  private
  def user_selected
    @user = User.find(current_user.id)
  end

  def user_signed_in_check
    redirect_to user_session_path unless user_signed_in?
  end

  def get_payjp_info
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
  end
end

app/controllers/mypage/listings_controller.rb
class Mypage::ListingsController < MypageController
  def listing
  end

  def in_progress
  end

  def completed
  end
  
end

app/controllers/mypage/nices_controller.rb
class Mypage::NicesController < MypageController
  def index
  end
end

app/controllers/mypage/reviews_controller.rb
class Mypage::ReviewsController < MypageController
  def index
  end

  def great
    render 'index'
  end

  def good
    render 'index'
  end
  
  def poor
    render 'index'
  end

  
  
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  before_action :user_signed_in_check
  before_action :user_selected

  def index
  end

  def notification
  end

  def todo
  end

  def purchase
  end

  def purchased
  end

  def review
  end

  def logout
  end

  def identification
  end

  def identification_update
    if @user.address.update(user_params[:address_attributes])
      redirect_to mypage_index_path
    else
      render :notification
    end
  end

  def edit
  end

  def profile
  end

  def profile_update
    if update_resource(@user, user_params)
      redirect_to mypage_index_path
    else
      render :profile
    end
  end

  private
  def user_selected
    @user = User.find(current_user.id)
  end

  def user_signed_in_check
    redirect_to user_session_path unless user_signed_in?
  end

  def user_params
    params.require(:user).permit(
      :nickname,
      :user_profile,
      address_attributes: [:zipcode, :prefecture_id, :city, :address, :phone_number],
      card_attributes: [:card_number, :validated_data, :security_code]
    )
  end

  protected
  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
end

app/views/mypage/_nav.html.haml
.mypage-nav
  %ul.mypage-nav__list
    %li
      =link_to "/mypage/" , class:"mypage-nav__list--item #{(controller_name == "mypage" && controller.action_name == "index") ? 'active' : ''}" do
        = "マイページ"
        =fa_icon 'chevron-right'
    %li
      =link_to "/mypage/notification/", class:"mypage-nav__list--item #{controller.action_name == "notification" ? 'active' : ''}" do
        お知らせ
        =fa_icon 'chevron-right'
    %li
      =link_to "/mypage/todo/", class:"mypage-nav__list--item #{controller.action_name == "todo" ? 'active' : ''}" do
        やることリスト
        =fa_icon 'chevron-right'
    %li
      =link_to "/mypage/nice/history/", class:"mypage-nav__list--item #{controller_name == "nices" ? 'active' : ''}" do
        いいね！一覧
        =fa_icon 'chevron-right'
    %li
      =link_to "/products/new/", class:"mypage-nav__list--item" do
        出品する
        =fa_icon 'chevron-right'
    %li
      =link_to "/mypage/listings/listing/", class:"mypage-nav__list--item #{controller.action_name == "listing" ? 'active' : ''}" do
        出品した商品 - 出品中
        =fa_icon 'chevron-right'
    %li
      =link_to "/mypage/listings/in_progress/", class:"mypage-nav__list--item #{controller.action_name == "in_progress" ? 'active' : ''}" do
        出品した商品 - 取引中
        =fa_icon 'chevron-right'
    %li
      =link_to "/mypage/listings/completed/", class:"mypage-nav__list--item #{controller.action_name == "completed" ? 'active' : ''}" do
        出品した商品 - 売却済み
        =fa_icon 'chevron-right'
    %li
      =link_to "/mypage/purchase/", class:"mypage-nav__list--item #{controller.action_name == "purchase" ? 'active' : ''}" do
        購入した商品 - 取引中
        =fa_icon 'chevron-right'
    %li
      =link_to "/mypage/purchased/", class:"mypage-nav__list--item #{controller.action_name == "purchased" ? 'active' : ''}" do
        購入した商品 - 過去の取引
        =fa_icon 'chevron-right'
    %li
      =link_to "/#", class:"mypage-nav__list--item" do  # "/mypage/news/"
        ニュース一覧
        =fa_icon 'chevron-right'
    %li
      =link_to "/mypage/review/history/", class:"mypage-nav__list--item #{controller_name == "reviews" ? 'active' : ''}" do
        評価一覧
        =fa_icon 'chevron-right'
    %li
      =link_to "/#", class:"mypage-nav__list--item" do #"/help_center/"
        ガイド
        =fa_icon 'chevron-right'
    %li
      =link_to "/#", class:"mypage-nav__list--item" do #"/mypage/support/"
        お問い合わせ
        =fa_icon 'chevron-right'

  .mypage-nav--head
    メルペイ
  %ul.mypage-nav__list
    %li
      =link_to "/#", class:"mypage-nav__list--item" do #"/mypage/sales/"
        売上・振込申請
        =fa_icon 'chevron-right'
    %li
      =link_to "/#", class:"mypage-nav__list--item" do # "/mypage/point/" 
        ポイント
        =fa_icon 'chevron-right'
  .mypage-nav--head
    設定
  %ul.mypage-nav__list
    %li
      =link_to "/mypage/profile/", class:"mypage-nav__list--item #{controller.action_name == "profile" ? 'active' : ''}" do
        プロフィール
        =fa_icon 'chevron-right'
    %li
      =link_to "/#", class:"mypage-nav__list--item" do #"/mypage/dliver_address/"
        発送元・お届け先住所変更
        =fa_icon 'chevron-right'
    %li
      =link_to "/mypage/card/", class:"mypage-nav__list--item #{(controller_name == "card") ? 'active' : ''}" do
        支払い方法
        =fa_icon 'chevron-right'
    %li
      =link_to "/#", class:"mypage-nav__list--item" do #"/mypage/email_password/"
        メール/パスワード
        =fa_icon 'chevron-right'
    %li
      =link_to "/mypage/identification/", class:"mypage-nav__list--item #{controller.action_name == "identification" ? 'active' : ''}"do
        本人情報
        =fa_icon 'chevron-right'
    %li
      =link_to "/#", class:"mypage-nav__list--item" do  #"/mypage/sms_confirmation/"
        電話番号の確認
        =fa_icon 'chevron-right'
    %li
      =link_to "/mypage/logout/", class:"mypage-nav__list--item #{controller.action_name == "logout" ? 'active' : ''}" do
        ログアウト
        =fa_icon 'chevron-right'

app/views/mypage/_purchase-list.html.haml
- if (products.length != 0)
  - products.each do |product|
    %li
      =link_to product_path(product.id), class:"mypage-link" do
        =image_tag product.images.first.image, class:"lazyload"
        .mypage-link__body
          .mypage-link__body--text
            - if (product.user_id != current_user.id && product.trade_status == 1)
              = "「#{product.item_name}」の取引中です。"
            - elsif (product.user_id != current_user.id && product.trade_status == 2)
              = "「#{product.item_name}」を購入しました。取引が完了しました"
          - if product.trade_status == 0
            .mypage-link__body--status.bold.awaiting
              出品中
          - elsif product.trade_status == 1
            .mypage-link__body--status.bold.awaiting
              取引中
          - else
            .mypage-link__body--status.bold.done
              取引完了
        =fa_icon 'chevron-right'
- else
  %li.mypage-link--notfound.bold
    - if controller.action_name == "purchase"
      取引中の商品がありません
    - elsif controller.action_name == "purchased"
      購入済みの商品がありません

app/views/mypage/identification.html.haml
- breadcrumb :identification
.mypage-wrapper
  .mypage.clearfix
    = render 'nav'
    .mypage__content      
      .mypages_container
        .user_information
          %section.idenfitication
            %h2.idenfitication 本人情報の確認
          = form_for @user, url: identification_update_mypage_index_path do |f|
            =f.fields_for :address, @user.address do |a|
              .idenfitication_contents
                .caution_message
                  %p.supplement
                    お客さまの本人情報をご登録ください。
                    %br 登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
                  .caution_message__text_right
                    %p.text_right
                      %a.detail_page{href: "http:twitter.com", target: "blank"}
                        本人確認書類のアップロードについて
                    
                .form_group
                  %label.idenfitication お名前
                  %p.idenfitication
                    =@user.firstname
                    =@user.lastname
                .form_group
                  %label.idenfitication お名前カナ
                  %p.idenfitication
                    =@user.firstname_kana
                    =@user.lastname_kana
                .form_group
                  %label.idenfitication{for: "birthday"} 
                    生年月日
                  %p.idenfitication
                    =@user.birthday.strftime("%Y/%m/%d")
                .form_group
                  %label.idenfitication{for: "zip_code"}
                    郵便番号
                  %span.form_arbitrary 任意
                = a.text_field :zipcode , { class:"input_default", placeholder:'例)1234567', value: "#{@user.address.zipcode}", required: true}
                .form_group
                  %label.idenfitication{for: "prefcture", class: "select_prefectures"}
                    都道府県
                  %span.form_arbitrary 任意
                  .select_wrap
                    .i.icon_arrow_bottom
                      = a.collection_select :prefecture_id, Prefecture.all, :id, :name, selected:@user.address.prefecture_id, class: 'default'
                .form_group
                  %label.idenfitication{for: "city"}
                    市区町村
                  %span.form_arbitrary 任意
                = a.text_field :city, { class:"input_default", placeholder:'例)横浜市緑区', value: "#{@user.address.city}", required: true}
                .form_group
                  %label.idenfitication{for: "adress"}
                    番地
                  %span.form_arbitrary 任意
                = a.text_field :address, { class:"input_default", placeholder:'例)青山1-1-1', value: "#{@user.address.address}"}
                .form_group
                  %label.idenfitication{for: "building_name"}
                    建物名
                  %span.form_arbitrary 任意
                = a.phone_field :building_name, { class:"input_default", placeholder:"例) 山田ビル101",value: "#{@user.address.building_name}"}
                =f.submit "登録する", class:"btn_red"
                .form_group
                  %p{class:"text_right"}
                    %a.detail_page{href: "http", target:"_blank"} 
                      本人情報の登録について

app/views/mypage/index.html.haml
- breadcrumb :mypage
.mypage-wrapper
  .mypage.clearfix
    = render 'nav'
    .mypage__content
      %section.mypage__user
        =link_to "ユーザーid毎のページurl",  class:"mypage__user--link" do
          = image_tag "//static.mercdn.net/images/member_photo_noimage_thumb.png", width:"60", height:"60"
          .mypage__user--name.bold<>
            = current_user.nickname
          .mypage__user--info
            %div<>
              評価
              %span.bold
                0
            %div
              出品数
              %span.bold
                =current_user.products.length
      %section.mypage__noti-todo
        %ul.noti-todo__select
          %li.active<>
            =link_to "#mypage-tab-notification", "data-toggle": "tab" do
              お知らせ
          %li<>
            =link_to "#mypage-tab-todo", "data-toggle": "tab" do
              やることリスト
        .noti-todo__content
          %ul#mypage-tab-notification.noti-todo__content.tab-pane.active
            %li
              =link_to "https://www.mercari.com/jp/mypage/news/", class: "mypage-link" do
                =image_tag "svg/logo_red.svg", class:"lazyloaded"
                .mypage-link__body
                  .mypage-link__body--text
                    事務局から個別メッセージ「Googleログイン通知」
                  %time
                    =fa_icon 'clock'
                    %span
                      3 時間前
                =fa_icon 'chevron-right'
            %li
              =link_to "https://www.mercari.com/jp/mypage/sales/bill/history/", class:"mypage-link" do
                =image_tag "svg/logo_red.svg", class:"lazyloaded"
                .mypage-link__body
                  .mypage-link__body--text
                    振込完了のお知らせ
                  %time
                    = fa_icon 'clock'
                    %span
                      22 時間前
                =fa_icon 'chevron-right'
            %li.notification-list
              =link_to "/mypage/notification/" do
                一覧を見る
          %ul#mypage-tab-todo.noti-todo__content.tab-pane
            %li.mypage-link--notfound.bold
              現在、やることリストはありません
      %section.mypage__transaction
        .mypage__transaction--head
          購入した商品
        %ul.transaction__select
          %li.active
            =link_to "#mypage-tab-transaction-now", "data-toggle": "tab" do
              取引中
          %li
            =link_to "#mypage-tab-transaction-old", "data-toggle": "tab" do
              過去の取引
        .transaction__content.clearfix
          %ul#mypage-tab-transaction-now.mypage-link--list.tab-pane.active
            = render partial: "purchase-list", locals: {products: @user.trade_products.where(trade_status: 1)}
            %li.purchased-list
              =link_to "/jp/mypage/purchase/" do
                一覧を見る
            .headerlists.clearfix
          %ul#mypage-tab-transaction-old.mypage-link--list.tab-pane
            = render partial: "purchase-list", locals: {products: @user.trade_products.where(trade_status: 2)}
            %li.purchased-list
              =link_to "/jp/mypage/purchased/" do
                一覧を見る
            .headerlists.clearfix

app/views/mypage/logout.html.haml
- breadcrumb :logout
.mypage-wrapper
  .mypage.clearfix
    =render 'mypage/nav'
    .mypage__content
      .wrapper
        .log-out
          =link_to destroy_user_session_path, method: :delete, class:"log-out__btn" do
            %span ログアウト

app/views/mypage/notification.html.haml
- breadcrumb :notification
.mypage-wrapper
  .mypage.clearfix
    = render 'nav'
    .mypage__content
      %section.mypage__noti-todo
        %ul.noti-todo__select
          %li.active<>
            =link_to "#mypage-tab-notification", "data-toggle": "tab" do
              お知らせ
          %li<>
            =link_to "/mypage/todo", "data-toggle": "tab" do
              やることリスト
        .noti-todo__content
          %ul#mypage-tab-notification.noti-todo__content.tab-pane.active
            %li
              =link_to "https://www.mercari.com/jp/mypage/news/", class: "mypage-link" do
                =image_tag "svg/logo_red.svg", class:"lazyloaded"
                .mypage-link__body
                  .mypage-link__body--text
                    事務局から個別メッセージ「Googleログイン通知」
                  %time
                    = fa_icon 'clock'
                    %span
                      3 時間前
                =fa_icon 'chevron-right'
            %li
              =link_to "https://www.mercari.com/jp/mypage/sales/bill/history/", class:"mypage-link" do
                =image_tag "svg/logo_red.svg", class:"lazyloaded"
                .mypage-link__body
                  .mypage-link__body--text
                    振込完了のお知らせ
                  %time
                    =fa_icon 'clock'
                    %span
                      22 時間前
                =fa_icon 'chevron-right'
          %ul#mypage-tab-todo.noti-todo__content.tab-pane
            %li.mypage-link--notfound.bold
              現在、やることリストはありません

app/views/mypage/payment.html.haml
.mypage-wrapper
  .mypage.clearfix
    = render 'nav'
    .mypage__content
      %section.mypage-payment
        .mypage-payment--head.head-center
          支払い方法
        .payment-info
          .payment-info__card
            .payment-info__card--head
              クレジットカード一覧
            - if true
              %ul.payment-info__list
                %li
                  %form{class:"cardform", action:"https://www.mercari.com/jp/mypage/card/delete/", method:"POST"}
                    =image_tag "//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?210491352", width:"49", height:"15", alt:"visa"
                    %input{type:"hidden", name:"__csrf_value", value:"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}
                    %input{type:"hidden", name:"card_sequence_no", value:"xxxxxxxxxxxxxxxxxxxxxxxx"}
                    .cardform--num<
                      ************ABCD
                    .cardform--num<
                      12 / 31
                    %input{type:"hidden", name:"method", value:"card"}
                    %button{type:"submit", class:"cardform--submit"}
                      削除する
            - else
              .payment-info__card--add-btn.red-btn
                = link_to "card-add" do
                  =fa_icon 'credit-card'
                  クレジットカードを追加する
            
          .payment-info--notregist
            =link_to "/help_center/category/6/", target:"_blank" do
              支払い方法について
              =fa_icon 'chevron-right'

app/views/mypage/profile.html.haml
- breadcrumb :profile
=render "homes/sell-btn"
=form_for @user, url: profile_update_mypage_index_path do |f|
  .mypage-wrapper
    .mypage.clearfix
      =render 'mypage/nav'
      .mypage__content
        .mypage__content-title
          プロフィール
        .mypage__content-imagebox
          %section.mypage__content-imagebox-user
            =link_to mypage_index_path,  class:"mypage__content-user--link" do
              = image_tag "//static.mercdn.net/images/member_photo_noimage_thumb.png", width:"60", height:"60"
            = f.text_field :nickname, class:"mypage__content-imagebox-user--name" ,value:@user.nickname

        .mypage__content-form
          =f.text_area :user_profile, value:@user.user_profile , class:"mypage__content-form--text"
          =f.submit '変更する', class:"mypage__content-form--btn"

app/views/mypage/purchase.html.haml
- breadcrumb :purchase
.mypage-wrapper
  .mypage.clearfix
    = render 'nav'
    .mypage__content
      %section.mypage__transaction
        .mypage__transaction--head
          購入した商品
        %ul.transaction__select
          %li.active
            =link_to "#mypage-tab-transaction-now", "data-toggle": "tab" do
              取引中
          %li
            =link_to "/mypage/purchased", "data-toggle": "tab" do
              過去の取引
        .transaction__content
          %ul#mypage-tab-transaction-now.mypage-link--list.tab-pane.active
            = render partial: "purchase-list", locals: {products: @user.trade_products.where(trade_status: 1)}
          %ul#mypage-tab-transaction-now.mypage-link--list.tab-pane
            = render partial: "purchase-list", locals: {products: @user.trade_products.where(trade_status: 2)}

app/views/mypage/purchased.html.haml
- breadcrumb :purchased
.mypage-wrapper
  .mypage.clearfix
    = render 'nav'
    .mypage__content
      %section.mypage__transaction
        .mypage__transaction--head
          購入した商品
        %ul.transaction__select
          %li
            =link_to "/mypage/purchase", "data-toggle": "tab" do
              取引中
          %li.active
            =link_to "#mypage-tab-transaction-now", "data-toggle": "tab" do
              過去の取引
        .transaction__content
          %ul#mypage-tab-transaction-now.mypage-link--list.tab-pane
            = render partial: "purchase-list", locals: {products: @user.trade_products.where(trade_status: 1)}
          %ul#mypage-tab-transaction-now.mypage-link--list.tab-pane.active
            = render partial: "purchase-list", locals: {products: @user.trade_products.where(trade_status: 2)}

app/views/mypage/todo.html.haml
- breadcrumb :todo
.mypage-wrapper
  .mypage.clearfix
    = render 'nav'
    .mypage__content
      %section.mypage__noti-todo
        %ul.noti-todo__select
          %li<>
            =link_to "/mypage/notification", "data-toggle": "tab" do
              お知らせ
          %li.active<>
            =link_to "#mypage-tab-todo", "data-toggle": "tab" do
              やることリスト
        .noti-todo__content
          %ul#mypage-tab-notification.noti-todo__content.tab-pane
            %li
              =link_to "https://www.mercari.com/jp/mypage/news/", class: "mypage-link" do
                =image_tag "svg/logo_red.svg", class:"lazyloaded"
                .mypage-link__body
                  .mypage-link__body--text
                    事務局から個別メッセージ「Googleログイン通知」
                  %time
                    = fa_icon 'clock'
                    %span
                      3 時間前
                =fa_icon 'chevron-right'
            %li
              =link_to "https://www.mercari.com/jp/mypage/sales/bill/history/", class:"mypage-link" do
                =image_tag "svg/logo_red.svg", class:"lazyloaded"
                .mypage-link__body
                  .mypage-link__body--text
                    振込完了のお知らせ
                  %time
                    =fa_icon 'clock'
                    %span
                      22 時間前
                =fa_icon 'chevron-right'
          %ul#mypage-tab-todo.noti-todo__content.tab-pane.active
            %li.mypage-link--notfound.bold
              現在、やることリストはありません