config/routes.rb
Rails.application.routes.draw do
  devise_for :users, module: :users, controllers: {
    :registrations => 'users/registrations',
    :omniauth_callbacks =>  "users/omniauth_callbacks"
  }

  devise_scope :user do
    scope :signup do
      get '/' => 'users/registrations#signup'
      get '/registration' => 'users/registrations#registration'
      get '/sms_confirmation' => 'users/registrations#sms_confirmation'
      get '/sms_confirmation/sms/' => 'users/registrations#sms_confirmation_check'
      get '/address_confirmation' => 'users/registrations#address_confirmation'
      get '/card_confirmation' => 'users/registrations#card_confirmation'
      post '/complete' => 'users/registrations#complete'
    end
  end
  resources :mypage, only: :index do
    collection do
      get 'notification' => 'mypage#notification'
      get 'todo' => 'mypage#todo'
      get 'purchase' => 'mypage#purchase'
      get 'purchased' => 'mypage#purchased'
      get 'logout' => 'mypage#logout'
      get 'identification' =>'mypage#identification'
      get 'profile' => 'mypage#profile'
      patch 'profile_update' => 'mypage#profile_update'
      patch 'identification_update' => 'mypage#identification_update'
      namespace :card do
        get '/' => '/mypage/card#show'
        get 'create' => '/mypage/card#edit'
        post 'update' => '/mypage/card#update'
      end
      namespace :listings do
        get 'listing' => '/mypage/listings#listing'
        get 'in_progress' => '/mypage/listings#in_progress'
        get 'completed' => '/mypage/listings#completed'
      end
      namespace :review do
        get 'history' => '/mypage/reviews#index'
        get 'history/great' => '/mypage/reviews#great'
        get 'history/good' => '/mypage/reviews#good'
        get 'history/poor' => '/mypage/reviews#poor'
      end
      namespace :nice do
        get 'history' => '/mypage/nices#index'
      end
    end
  end

  resources :category, only: :show
  resources :brand, only: :show
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :trade, except: :index do
    collection do
      post 'pay/:id' => 'products#pay', as: 'pay'
    end
  end

  resources :products, except: :index do
    collection do
      get 'search'
    end
  end


  resources :products, except: :index do
    member do
      get :confirmation
    end
  end
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products, except: :index
  resource :card, controller: :card do
    collection do
      post 'pay/:id' => 'card#pay', as: 'pay'
    end
  end




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "homes#index"
  get 'products/:id/edit' => 'products#update'

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :images,dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy:true

  # has_many :commnets
  # has_many :messages
  # has_many :nices

  has_one :trade 
  belongs_to :user,optional:true
  belongs_to :category,optional:true
  belongs_to :bland,optional:true
  validates :item_name,presence:true
  validates :description,presence:true
  validates :item_condition,presence:true
  validates :trade_status,presence:true
  validates :category_id,presence:true
  validates :delivery_charge,presence:true
  validates :delivery_method,presence:true
  validates :delivery_area,presence:true
  validates :delivery_time,presence:true
  validates :price,presence:true
  validates :user_id,presence:true
  

#######enum用です#######################
  enum size:{'XXS以下':0,'XS(SS)':1,'S':2,'M':3,'L':4,'XL(LL)':5,'2XL(3L)':6,'3XL(4L)':7,'4XL(5L)以上':8,'FREESIZE':9}
  enum delivery_time:{'1~2日で発送':0,'2~3日で発送':1,'4~7日で発送':2}
  enum delivery_method:{'未定':0,'らくらくメルカリ便':1,'ゆうメール':2,'レターパック':3,'普通郵便(定型、定形外)':4,'クロネコヤマト':5,'ゆうパック':6,'クリックポスト':7,'ゆうパケット':8}
  enum delivery_charge:{'送料込み':0,'着払い':1}
  enum delivery_area:{'北海道':0,'青森県':1,'岩手県':2,'宮城県':3,'秋田県':4,'山形県':5,'福島県':6,'茨城県':7,'栃木県':8,'群馬県':9,'埼玉県':10,'千葉県':11,'東京都':12,'神奈川県':13,'新潟県':14,'富山県':15,'石川県':16,'福井県':17,'山梨県':18,'長野県':19,'岐阜県':20,'静岡県':21,'愛知県':22,'三重県':23,'滋賀県':24,'京都府':25,'大阪府':26,'兵庫県':27,'奈良県':28,'和歌山県':29,'鳥取県':30,'島根県':31,'岡山県':32,'広島県':33,'山口県':34,'徳島県':35,'香川県':36,'愛媛県':37,'高知県':38,'福岡県':39,'佐賀県':40,'長崎県':41,'熊本県':42,'大分県':43,'宮崎県':44,'鹿児島県':45,'沖縄県':46}
  enum item_condition:{ '新品、未使用に近い':0,'未使用に近い':1,'目立った傷や汚れなし':2,'やや汚れや傷あり':3,'傷や汚れあり':4,'全体的に状態が悪い':5 }
###########################################
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :select_product, {except:[:new, :create, :search]}
  before_action :user_signed_in_check, only: [:new, :create, :destroy, :confirmation]


  def new
    @product = Product.new
    @product.images.build
  #//////カテゴリ、ブランド用////////
    @parents = Category.sort_parents
    @parent = Category.find(params[:category_id]) if params[:category_id].present?
    @child = Category.find(params[:child_id])     if params[:child_id].present?
    @search = params[:bland_name]
    @all_products = Product.all

    if @parent && @child && @search
      @blands1 = @parent.blands
      @blands2 = @child.blands
      if @blands2.empty?
        @blands = @blands1.search_name(params[:bland_name])
      else
        @blands = @blands2.search_name(params[:bland_name])
      end
    elsif @parent && @child ==nil && @search==nil
      @children = @parent.children
    elsif @child && @parent ==nil && @search==nil
      @grand_children = @child.children
    end

    respond_to do |format|
      format.html
      format.json
    end
  end

  def create
    @product = Product.new(product_params)
      if @product.save
      else
        redirect_to action: :new ,flash: {error:'エラーが発生しました、再度入力をお願いします'}
    end
  end

  def show
    @images = @product.images.order("created_at ASC").limit(10)
    if @product.bland
      @similar_items = Product.where.not(
        params[:id]
      ).where(
        category_id: @product.category.id, bland_id: @product.bland.id).limit(6)
    else
      @similar_items = Product.where.not(
        params[:id]
      ).where(
        category_id: @product.category.id).limit(6)
    end
    @same_seller_items = Product.where.not(params[:id]).where(user_id: @product.user.id).limit(6)
 
  end

  def edit
    #//////カテゴリ、ブランド用////////
      @parents = Category.sort_parents
      @parent = Category.find(params[:category_id]) if params[:category_id].present?
      @child = Category.find(params[:child_id])     if params[:child_id].present?
      @search = params[:bland_name]

      if @parent && @child && @search
          @blands1 = @parent.blands
          @blands2 = @child.blands
        if @blands2.empty?
            @blands = @blands1.search_name(params[:bland_name])
        else
            @blands = @blands2.search_name(params[:bland_name])
        end
      elsif @parent && @child ==nil && @search==nil
        @children = @parent.children
      elsif @child && @parent ==nil && @search==nil
        @grand_children = @child.children
      end
      respond_to do |format|
        format.html
        format.json
      end
  end

  def update
    if @product.update(product_params)
      del_num = params[:del_img].split(",")
      del_num.each do |d|
        @product.images[d.to_i].destroy
      end
      redirect_to action: :show
    else
      redirect_to action: :show,flash: {error:'エラーが発生しました。編集できませんでした。'}
    end
  end

  def search
      @product = Product.new
      @category = Category.sort_parents
      @parent = Category.find(params[:category_id]) if params[:category_id].present?
      @child = Category.find(params[:child_id]) if params[:child_id].present?
      @blands = Bland.where('name LIKE ?',"%#{params[:bland_name]}") unless params[:bland_name].empty? if params[:bland_name]
      @children = @parent.children if @parent
      @grand_children = @child.children if @child

      ##########カテゴリ配列処理###########
      @category_ids = @parent.descendant_ids << @parent.id if @parent
      ##########カテゴリの追加検索###############
      # Product.where(category_id:@category_ids)

      @sort = "#{params[:sort]}"
      @p = Product.ransack(search_name) if @sort
      @products = @p.result if @p
      @products = @products.order(@sort).page(params[:page]).per(20) if @products
      @products = @products.where(category_id:@category_ids) if @category_ids.present?

      @search_name = search_name
      @new_products = Product.where(updated_at:Time.now.all_year).page(params[:page]).per(20)
      @word = search_name[:item_name_or_description_cont] if search_name[:item_name_or_description_cont]

     #### ヘッダー利用時、商品名のみの検索結果のソート#################
      if params[:name].present?
          @products = Product.where('item_name LIKE ?',"%#{params[:name]}%").page(params[:page]).per(20)
          @word = params[:name]
          @products = @products.order(@sort).page(params[:page]).per(20) if @sort
      end

      respond_to do |format|
        format.html
        format.json
      end
  end

  def destroy
    @product.destroy
    if @product.destroy
      redirect_to root_path
    else
      redirect_to action: :show,flash: {error:'エラーが発生しました。削除できませんでした。'}
    end
  end

  private
  def select_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:item_name,:description,:item_condition,:trade_status,:size,:bland_id,:category_id,:delivery_charge,:delivery_method,:delivery_area,:delivery_time,:price,:trade_status,images_attributes: [:destroy,:id,:image]).merge(user_id:current_user.id)
  end

  def user_signed_in_check
    redirect_to user_session_path unless user_signed_in?
  end

  def search_name
      params.permit(:name,:item_name_or_description_cont,:bland_name,:category_id,:price_gteq,:price_lteq,:sort,:utf8,bland_id_eq_any:[],category_id_eq_any:[], size_eq_any:[],item_condition_eq_any:[],delivery_charge_eq_any:[],trade_status_eq_any:[])
  end

end

app/views/products/confirmation.html.haml
.header_logo
  =image_tag "svg/fmarket_logo_red.svg", class: "header_logo__confirmation"
.trade_confirmation
  .trade_confirmation__width_main
    #h2.header_message
      購入内容の確認
    #seciton.buy_contents
      .buy_contents__width_buyArea
        .buy_contents__width_buyArea--item_image
          = image_tag "#{@product.images.first.image}", class:"buy_contents__width_buyArea--trade_item"

        .buy_contents__width_buyArea--item_name
          = @product.item_name
        .buyForm
          .buyArea 
            .buyArea__buyPrice 
              = "￥#{@product.price.to_s(:delimited)}"
            .buyArea__shippingFee 
              送料込み
          .point_box
            .point_box__point_area  
              ポイントはありません
          .pay_area
            .pay_area__pay_message  
              支払い金額
            .pay_area__pay_price  
              ="¥#{@product.price.to_s(:delimited)}"
          .error_message  
            配送先と支払い方法の入力を完了してください。
          = form_tag("/card/pay/1", method: :post,class: :btn_grey) do
            = hidden_field_tag :product_id, @product.id 
            %script.payjp-button{src: "https://checkout.pay.jp/" , "data-key": ENV["PAYJP_PUBLIC_KEY"] ,"data-text": "購入する"}

    #section.contents_box{class:"delivery_contents"}
      .contents_box__inner
        #h3.dataTitle
          配送先
        #adress.buy_userInfo--postal 
          = "〒#{current_user.address.zipcode}"
        #adress.buy_userInfo--street  
          = "#{current_user.address.prefecture.name}#{current_user.address.city}#{current_user.address.address}"
        #adress.buy_userInfo--name  
          = "#{current_user.firstname} #{current_user.lastname}"
        #p.buy_userInfo  
          = current_user.address.building_name
        %ul.fix
          %li.delivery_fix(id="fix-category")
            =link_to "/#" ,class:'userInfo-fix' do
              変更する >
    #section.contents_box{class:"pay_contents"}
      .contents_box__inner
        #h3.dataTitle 
          支払い方法
        .adress.postalCode /
        %ul.fix
          %li.pay_fix(id="fix-category")
            =link_to "/#" ,class:'userInfo-fix' do
              変更する >
.fooder_area 
  .footer
    %ul.footer--nav.clearfix
      %li<
        = link_to "." do
          プライバシーポリシー 
      %li<
        = link_to "." do
          メルカリ利用規約
      %li<
        = link_to "." do
          特定商取引に関する表記
    =link_to root_path, class:"footer--img" do
      =image_tag "svg/logo_gray.svg"
    .footer--text
      © 2019 Mercari 

app/views/products/search.html.haml
.search_backgournd
  .search_contents.clearfix
    .sidebar_contents
      =form_tag(search_products_path,method:'get',id:'search_product') do
        .sort
          = select_tag 'sort_search', options_for_select({'価格の安い順': 'price ASC', '価格の高い順': 'price DESC', '出品の古い順': 'created_at ASC','出品の新しい順':'created_at DESC','いいねの多い順':''}, 1), include_blank: '並べ替え',class:'form_box'

        .search_box
          %p.tittle 詳細検索
          .search_box__form
            %p.key
              =fa_icon 'plus'
              キーワードを追加する
            =text_field_tag :item_name_or_description_cont,"",id:'search_field',class:'form_box',placeholder:'例)値下げ'
          .search_box__form
            %p.key
              =fa_icon 'bars'
              カテゴリーを選択する
            =select_tag 'category_id',options_from_collection_for_select(@category,:id,:name,0),class:'form_box', include_blank: 'すべて',id:'parent_category_id'
          .search_box__form
            %p.key
              =fa_icon 'tags'
              ブランド名から探す
            =text_field_tag :bland_name,'',id:'search_bland_field',class:'form_box',placeholder:'例)シャネル'
            =text_field_tag 'bland_id_eq_any[]','',id:'bland_hidden_form'
          .search_box__form--size
            %p.key
              =fa_icon 'check-square'
              サイズを指定する
            = select_tag 'category_id_eq_any[]', options_for_select({'メンズ服のサイズ': '2', 'レディース服のサイズ': '1', 'ベビー服のサイズ': '3'}, ''), include_blank: 'すべて',class:'form_box',id:'size_form'
            .sizeform
              - n=0
              -Product.sizes.each do |i|
                =check_box_tag 'size_eq_any[]',"#{n}",{multiple:true,include_blank:'',checked:false},class:'size_check'
                =label_tag :size,"#{i[0]}"
                - n+=1

          .search_box__form
            %p.key
              =fa_icon 'bitcoin'
              価格

            = select_tag '', options_for_select({'300~1000':'300~1000', '1000~5000':'1000~5000', '5000~10000':'5000~10000','10000~30000':'10000~30000','30000~50000':'30000~50000','50000~':'50000~',}, 1), include_blank: true,class:'form_box',id:"price_form"
            = text_field_tag :price_gteq,"",id:'price_min',class:'form_box_half',placeholder:'¥min'
            %p.symbol ~
            =text_field_tag :price_lteq,"",id:'price_max',class:'form_box_half',placeholder:'¥max'
          .search_box__form
            %p.key
              =fa_icon 'star'
              商品の状態
            =check_box_tag 'item_condition_eq_any[]',"",{multiple:true,include_blank:''},checked:false,class:'item_condition_check'
            =label_tag :"すべて"
            - n=0
            -Product.item_conditions.each do |i|
              =check_box_tag 'item_condition_eq_any[]',"#{n}",{multiple:true,checked:false},class:'item_condition_check'
              =label_tag :"#{i[0]}"
              - n+=1

          .search_box__form
            %p.key
              =fa_icon 'truck'
              配送料の負担
            =check_box_tag 'delivery_charge_eq_any[]',"",{multiple:true,include_blank:''},checked:false,class:'delivery_charge_check'
            =label_tag :"すべて"
            - n=0
            -Product.delivery_charges.each do |i|
              =check_box_tag 'delivery_charge_eq_any[]',"#{n}",{multiple:true,include_blank:''},checked:false,class:'delivery_charge_check'
              =label_tag :"#{i[0]}"
              - n+=1

          .search_box__form
            %p.key
              =fa_icon 'cart-plus'
              販売状況
            =check_box_tag 'trade_status_eq_any[]',"",{multiple:true,include_blank:''},checked:false,class:'trade_stastus_check'
            =label_tag :"すべて"
            =check_box_tag 'trade_status_eq_any[]',"0",{multiple:true,include_blank:''},checked:false,class:'trade_stastus_check'
            =label_tag :"販売中"
            =check_box_tag 'trade_status_eq_any[]',"1",{multiple:true,include_blank:''},checked:false,class:'trade_stastus_check'
            =label_tag :'売り切れ'

          .search_box__btn
            .search_box__btn--clear
              クリア
          .search_box__btn
            .search_box__btn--submit
              =submit_tag '完了'



    .maincontents
      -unless @products.empty? || @products.nil?
        -if @word.blank?
          %p.tittle
            検索結果
        -else
          %p.tittle
            #{@word}
          %p
            の検索結果
        %p.result
          1-#{@products.length}件の表示
        .products_contents
          -@products.each do |p|
            =link_to product_path(p) do
              .product
                .product__image
                -if p.images[0]
                  -@i =p.images[0]
                  = image_tag "#{@i.image}", class:"search_img"
                .product__price
                  ¥
                  =number_with_delimiter(p.price)
                .product__name
                  =p.item_name
          =paginate @products ,class:'page'

      -else
        %p.tittle #{@word}の検索結果
        %p.text 該当する商品が見つかりません。検索条件を変えて、再度お試しください。
        %br
        %br
        %p.tittle 新着商品
        .products_contents
          -@new_products.each do |p|
            .product
              .product__image
                -@i =p.images[0]
                = image_tag "#{@i.image}", class:"search_img"
              .product__price
                ¥
                =number_with_delimiter(p.price)
              .product__name
                =p.item_name
          =paginate @new_products

//////////////ソート用のフォームです/////////////////////////////////

=form_tag(search_products_path,method:'get',class:'sort_link') do
  =hidden_field_tag :sort,"",id:'sort_link_box',class:'sort_link_box'
  =hidden_field_tag :name,"#{@search_name[:name]}",id:'sort_word',class:'sort_word'
  =hidden_field_tag :item_name_or_description_cont,"#{@search_name[:item_name_or_description_cont]}"
  =hidden_field_tag :bland_name,"#{@search_name[:bland_name]}"
  =hidden_field_tag :price_gteq,"#{@search_name[:price_gteq]}"
  =hidden_field_tag :category_name,"#{@search_name[:category_name]}"
  =hidden_field_tag :category_id,"#{@search_name[:category_id]}"

  - if @search_name[:category_id_eq_any]
    -@search_name[:category_id_eq_any].each do |c|
      =hidden_field_tag 'category_id_eq_any[]',"#{c}"
  - if @search_name[:bland_id_eq_any]
    -@search_name[:bland_id_eq_any].each do |b|
      =hidden_field_tag 'bland_id_eq_any[]',"#{b}"

  =hidden_field_tag :price_lteq,"#{@search_name[:price_lteq]}"
  =hidden_field_tag :price_gteq,"#{@search_name[:price_gteq]}"
  -unless @search_name[:size_eq_any]==nil
    =hidden_field_tag 'size_eq_any[]',"#{@search_name[:size_eq_any]}"
  -unless @search_name[:item_condition_eq_any]==nil
    =hidden_field_tag 'item_condition_eq_any[]',"#{@search_name[:item_condition_eq_any]}"
  -unless @search_name[:delivery_charge_eq_any]==nil
    =hidden_field_tag 'delivery_charge_eq_any[]',"#{@search_name[:delivery_charge_eq_any]}"
  -unless @search_name[:trade_status_eq_any]==nil
    =hidden_field_tag 'trade_status_eq_any[]',"#{@search_name[:trade_status_eq_any]}"

  =submit_tag '', class:'sort_link_btn'

app/views/products/show.html.haml
.detail-wrapper
  .item
    .item__title
      = @product.item_name
    .item__image
      .item__image--main
        = image_tag "#{@images[0].image}", class:"main-image"
        -if @product.trade_status != 0
          .sold_out
            =image_tag "icons/sold_out.png",class:"sold_out"
      .item__image--sub
        -@images.each do |image|
          = image_tag "#{image.image}", class:"img"

    %table.item__detail
      %tr.big
        %th.gray
          出品者
        %th.seller
          =link_to "#" ,class:"name"do
            = @product.user.nickname
          =image_tag "icons/smile-face.png",class:"face"
          %span 1
          =image_tag "icons/normal-face.png",class:"face"
          %span 1
          =image_tag "icons/frown-face.png",class:"face"
          %span 1
      %tr.big
        %th.gray
          カテゴリー
        %th
          =link_to "/category/#{@product.category.root.id}" ,class:"link"do
            =">#{@product.category.root.name}"
          -if @product.category.id >= 159
            =link_to "/category/#{@product.category.parent.id}" ,class:"link"do
              =">#{@product.category.parent.name}"
          =link_to "/category/#{@product.category.id}" ,class:"link"do
            =">#{@product.category.name}"
      %tr
        %th.gray
          ブランド
        %th.brand
          -if @product.bland
            =link_to "/brand/#{@product.bland.id}" ,class:"link"do
              =@product.bland.name
      -if @product.size
        %tr
          %th.gray
            商品のサイズ
          %th
            =@product.size
      %tr
        %th.gray
          商品の状態
        %th
          =@product.item_condition
      %tr
        %th.gray
          配送料の負担
        %th
          =@product.delivery_charge
      %tr
        %th.gray
          配送の方法
        %th
          =@product.delivery_method
      %tr
        %th.gray
          配送元地域
        %th
          =link_to "#" ,class:"link"do
            =@product.delivery_area
      %tr
        %th.gray
          発送日の目安
        %th
          =@product.delivery_time
    .item__price
      ="￥#{@product.price.to_s(:delimited)}"
    .tax
      (税込)
    .postage
      送料込み
    -if user_signed_in?
      -if @product.user.id != current_user.id && @product.trade_status == 0
        =link_to confirmation_product_path(@product) ,class:"item__buy-btn"do
          購入画面に進む
        .caution
          この商品はゆうゆうメルカリ便を利用しているため、アプリからのみ購入できます。

      -if @product.trade_status != 0
        .item__buy-btn-gray
          売り切れました
    -else
      -if @product.trade_status == 0
        =link_to confirmation_product_path(@product) ,class:"item__buy-btn"do
          購入画面に進む
        .caution
          この商品はゆうゆうメルカリ便を利用しているため、アプリからのみ購入できます。
      -else
        .item__buy-btn-gray
          売り切れました

    .item__text
      =@product.description
    -if user_signed_in?
      -if @product.user.id != current_user.id
        .item__bottom
          %p.nice-btn
            =link_to "#" do
              =fa_icon "heart"
              %span
                いいね！
          %p.report-btn
            =link_to "#" do
              =fa_icon "flag"
              %span
                不適切な商品の報告
          =link_to "#",class:"safe_and_relief" do
            =fa_icon "shopping-bag"
            あんしん・あんぜんへの取り組み
    -else
      .item__bottom
        %p.nice-btn
          =link_to "#" do
            =fa_icon "heart"
            %span
              いいね！
        %p.report-btn
          =link_to "#" do
            =fa_icon "flag"
            %span
              不適切な商品の報告
        =link_to "#",class:"safe_and_relief" do
          =fa_icon "shopping-bag"
          あんしん・あんぜんへの取り組み

  -if user_signed_in?
    -if @product.user.id == current_user.id && @product.trade_status == 0
      .edit__content
        .edit__content-update-btn
          =link_to '商品の編集', edit_product_path(@product.id)
        %p.edit__content-or
        .edit__content-stop-btn
          =link_to '出品を一旦停止する'
        .edit__content-delete-btn
          =link_to 'この商品を削除する', product_path(@product.id), method: :delete, data: { confirm: '削除しますか？' }
  -else
  .comment
    .comment__caution
      %span
        相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります
    %textarea.comment__form
    =link_to "#" ,class:"comment__btn"do
      コメントする
  .other-item
    =link_to "#" ,class:"other-item__left"do
      < EGOIST エゴイスト　デニム
    =link_to "#" ,class:"other-item__right"do
      イエナ コート チェスター 23区 ネイビー >
  .icons
    =link_to "#" do
      =image_tag "icons/facebook.png",class:"icons__btn"
    =link_to "#" do
      =image_tag "icons/twitter.png",class:"icons__btn"
    =link_to "#" do
      =image_tag "icons/pinterest.png",class:"icons__btn"

  .same-seller-item
    =link_to "#",class:"title"do
      ="#{@product.user.nickname}さんのその他の出品"
      .products
        -@same_seller_items.each do |same_seller_item|
          .products-box
            =link_to product_path(same_seller_item) do
              .products-box__image
                =image_tag "#{same_seller_item.images.first.image}",class:"item-image"
                -if same_seller_item.trade_status != 0
                  .sold_out
                    =image_tag "icons/sold_out.png",class:"sold_out"
              .products-box__text
                =same_seller_item.item_name
              .products-box__bottom
                .price
                  ="¥#{same_seller_item.price.to_s(:delimited)}"
                =fa_icon "heart",class:"nice"
                %span
                  1

  -if @product.bland_id.present?
    .similar-item
      =link_to "#",class:"title"do
        ="#{@product.bland.name} #{@product.category.name} その他の出品"
        .products
          -@similar_items.each do |similar_item|
            .products-box
              =link_to product_path(similar_item) do
                .products-box__image
                  =image_tag "#{similar_item.images.first.image}",class:"item-image"
                  -if similar_item.trade_status != 0
                    .sold_out
                      =image_tag "icons/sold_out.png",class:"sold_out"
                .products-box__text
                  =similar_item.item_name
                .products-box__bottom
                  .price
                    ="¥#{similar_item.price.to_s(:delimited)}"
                  =fa_icon "heart",class:"nice"
                  %span
                    1
  -else
    .similar-item
      =link_to "#",class:"title"do
        ="#{@product.category.name}(#{@product.category.root.name}) その他の出品"
        .products
          -@similar_items.each do |similar_item|
            .products-box
              =link_to product_path(similar_item) do
                .products-box__image
                  =image_tag "#{similar_item.images.first.image}",class:"item-image"
                  -if similar_item.trade_status != 0
                    .sold_out
                      =image_tag "icons/sold_out.png",class:"sold_out"
                  .products-box__text
                    =similar_item.item_name
                  .products-box__bottom
                    .price
                      ="¥#{similar_item.price.to_s(:delimited)}"
                    =fa_icon "heart",class:"nice"
                    %span
                      1